# Paramètres du Dataset

f_min : 0.00199             # en Hz
interval_freq : 6e-6        # en Hz
num_samples : 100000           
Tobs : 1                    # nombre d'années
dt : 15
N : 128                     # nombre de points
chunk_size : 1000
Nom_Waveforms_h5 : "Waveform.h5"
Nom_Parametres_h5 : "Parameters_standardized.h5"
Nom_MeanVar_h5 : "MeanVar.h5"
nom_dossier_Dataset : "1e5"
alpha : 0                   # niveau de bruit






