# Paramètres de l'entrainement

hidden_dims : [300, 300]
Nom_dossier_Dataset : "1e6_amp_f0_iota_phi0_fdot_fixe"
Dataset_Waveform : "Waveform.h5"
Dataset_Parametre : "Parameters_standardized.h5"
MeanVar : "MeanVar.h5"
train_fraction : 0.8
batch_size : 256
lr : 0.0001
epochs : 20
nom_dossier_Train : "1e6_amp_f0_iota_phi0_fdot_fixe_300_300_e=20"
alpha : 0
taille_histo : 1000