# Paramètres du Dataset

f_min : 0.00199             # en Hz
interval_freq : 6e-6        # en Hz
F_max : 0  #1              1 pour aller de f_min à f_max et 0 pour avoir la frequence f0 constante
amp_min : 1e-21 #1e-23
amp_max : 1e-21
iota_min : 0
iota_max : 0  #3.141592
fdot_min : 7.538331e-18
fdot_max : 7.538331e-18 #7.538331e-16
phi0_min : 0
phi0_max : 0 #6.283184
psi_min : 0
psi_max : 3.141592
lam_min : -3.141592
lam_max : 3.141592
beta_sky_min : -1.570796
beta_sky_max : 1.570796
num_samples : 100          
Tobs : 1                    # nombre d'années
dt : 15
N : 128                     # nombre de points
chunk_size : 1e6
Nom_Waveforms_h5 : "Waveform.h5"
Nom_Parametres_h5 : "Parameters_standardized.h5"
Nom_MeanVar_h5 : "MeanVar.h5"
nom_dossier_Dataset : "1e6_amp_f0_iota_phi0_fdot_fixe"
alpha : 0                   # niveau de bruit








