# Paramètres de l'entrainement

hidden_dims : [50, 50]
Nom_dossier_Dataset : "1e5"
Dataset_Waveform : "Waveform.h5"
Dataset_Parametre : "Parameters_standardized.h5"
train_fraction : 0.8
batch_size : 256
lr : 0.0001
epochs : 50
nom_dossier_Train : "Entrainement_1e5_50_50_epoch=50"
alpha : 0

