# Paramètres de l'entrainement

hidden_dims : [1000, 1000]
Nom_dossier_Dataset : "Test"
Dataset_Waveform : "WaveformTest.h5"
Dataset_Parametre : "Parameters_standardizedTest.h5"
train_fraction : 0.8
batch_size : 256
lr : 0.0001
epochs : 20
nom_dossier_Train : "Train1"
alpha : 0

