# Paramètres du Dataset

f_min : 0.00199             # en Hz
interval_freq : 6e-6        # en Hz
F_max : 0  #1              1 pour aller de f_min à f_max et 0 pour avoir la frequence f0 constante
amp_min : 1e-21 #1e-23
amp_max : 1e-21
iota_min : 0
iota_max : 0  #3.141592
num_samples : 1e6          
Tobs : 1                    # nombre d'années
dt : 15
N : 128                     # nombre de points
chunk_size : 1000
Nom_Waveforms_h5 : "Waveform.h5"
Nom_Parametres_h5 : "Parameters_standardized.h5"
Nom_MeanVar_h5 : "MeanVar.h5"
nom_dossier_Dataset : "1e6_amp_f0_iota_fixe"
alpha : 0                   # niveau de bruit








